import discord
import random
import datetime
import requests
import json
from discord.ext import commands

class AgentCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.slash_command(name='agent', description="Have the bot randomly select an Agent for you!")
    async def agent(self, ctx: discord.commands.context.ApplicationContext):
        '''Have the bot randomly select an Agent for you!'''
    
        await ctx.respond('Select an Agent Type!', view= AgentView())

class AgentView(discord.ui.View):
    @discord.ui.select(
        placeholder = 'Choose an Agent Type!',
        min_values = 1,
        max_values = 1,
        options = [
            discord.SelectOption(
                label='Random Type',
                value='Random'
            ),
            discord.SelectOption(
                label='Controller',
            ),
            discord.SelectOption(
                label='Duelist',
            ),
            discord.SelectOption(
                label='Initiator',
            ),
            discord.SelectOption(
                label='Sentinel',
            )
        ]
    )
    async def callback(self, select, interaction):
        selectedAgentList = list()
        agentType = select.values[0]
        try:
            response = requests.get('https://valorant-api.com/v1/agents?isPlayableCharacter=true')
            if response.status_code != 200:
                raise Exception('Status Code not 200')
            fullAgentList = json.loads(response.content)['data']
        except:
            await interaction.response.edit_message(content='**ERROR:** Non 200 Status Code Recieved', view=None)

        for agent in fullAgentList:
            if agentType != 'Random':
                if agent['role']['displayName'] == agentType:
                    selectedAgentList.append({'name': agent['displayName'], 'type': agent['role']['displayName'], 'url': agent['displayIcon']})
            else:
                selectedAgentList.append({'name': agent['displayName'], 'type': agent['role']['displayName'], 'url': agent['displayIcon']})

        selectedAgent = random.choice(selectedAgentList)

        embed=discord.Embed(title='Valorant Agent Randomizer', color = discord.Colour.random())
        embed.set_thumbnail(url=selectedAgent['url'])
        embed.add_field(name=selectedAgent['name'], value=selectedAgent['type'])
        embed.set_footer(text='Requested by ' + interaction.user.display_name + ' at ' + datetime.datetime.now().strftime(r'%I:%M %p'))

        print('Agent Generated by', interaction.user.display_name, 'is', selectedAgent['name'])
        await interaction.response.edit_message(content='Selected Agent Type: ' + agentType, embed=embed, view=None)

def setup(bot):
    bot.add_cog(AgentCog(bot))
    print('Cog loaded: Agent')