import discord
import random
import datetime
from discord.ext import commands

class CrosshairCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.crosshairCode = '0'
        self.mainColor = format(random.randint(0, 16777215), "x").upper()

    @commands.slash_command(name='crosshair', description='Have the bot randomly generate a crosshair for you!')
    async def crosshair(self, ctx: discord.commands.context.ApplicationContext):
        
        self.genCrosshair()
        rgb_tuple = tuple(int(self.mainColor[i:i+2], 16) for i in (1, 3, 5))
        crossbed=discord.Embed(title='Valorant Crosshair Generator', 
                               description='Good Luck, Have Fun', 
                               color = discord.Colour.from_rgb(rgb_tuple[0], rgb_tuple[1], rgb_tuple[2]))
        crossbed.add_field(name='Profile Code', value=self.crosshairCode, inline=True)
        crossbed.set_footer(text='Requested by ' + ctx.author.display_name + ' at ' + datetime.datetime.now().strftime(r'%I:%M %p'))
        print('Crosshair generated by', ctx.author.display_name)
        await ctx.respond(embed=crossbed)

    def chance(self, pcnt):
        return random.random() < (pcnt / 100)
    
    def getRandomNumber(self, min_value: int, max_value: int, precision=0):
        random_number = random.uniform(min_value, max_value)
        return round(random_number, precision)

    def crosshairSettings(self):
        showCenterDot = self.chance(50)
        showOutlines = self.chance(50)
        firingErrorOverride = self.chance(50)

        showInnerLines = self.chance(70)
        innerLineLengthLinked = self.chance(50)
        innerMovementError = self.chance(50)
        innerFiringError = self.chance(50)

        showOuterLines = self.chance(70)
        outerLineLengthLinked = self.chance(50)
        outerMovementError = self.chance(50)
        outerFiringError = self.chance(50)

        # Base Color
        self.crosshairCode += f';P;c;8;u;{self.mainColor}FF;b;1' #;c;8 - Custom color

        # Outlines
        if showOutlines:
            self.crosshairCode += f';o;{self.getRandomNumber(0, 1, 3)}' # Opacity
            self.crosshairCode += f';t;{self.getRandomNumber(1, 6)}' # Thickness
        else:
            self.crosshairCode += ';h;0' # No Outline

        # Center Dot
        if showCenterDot:
            self.crosshairCode += f';d;1' # Center Dot Enable
            self.crosshairCode += f';a;{self.getRandomNumber(0, 1, 3)}' # Opacity
            self.crosshairCode += f';z;{self.getRandomNumber(1, 6)}' # Thickness

        # Firing Error
        if firingErrorOverride: self.crosshairCode += ';m;1'

        # Inner Lines
        if showInnerLines:
            self.crosshairCode += f';0a;{self.getRandomNumber(0, 1, 3)}' # Opacity
            self.crosshairCode += f';0l;{self.getRandomNumber(0, 20)}' # Horizontal Length
            self.crosshairCode += f';0v;{self.getRandomNumber(0, 20)}' # Vertical Length
            if not innerLineLengthLinked: self.crosshairCode += ';0g;1' # Lengths Linked
            self.crosshairCode += f';0t;{self.getRandomNumber(0, 10)}' # Thickness
            self.crosshairCode += f';0o;{self.getRandomNumber(0, 20)}' # Offset

            if innerMovementError:
                self.crosshairCode += ';0m;1' # Enable
                self.crosshairCode += f';0s;{self.getRandomNumber(0, 3, 3)}' # Multipler
            
            if innerFiringError:
                self.crosshairCode += f';0e;{self.getRandomNumber(0, 3, 3)}' # Multipler
            else:
                self.crosshairCode += ';0f;0' # Disable

        # Outer Lines
        if showOuterLines:
            self.crosshairCode += f';1a;{self.getRandomNumber(0, 1, 3)}' # Opacity
            self.crosshairCode += f';1l;{self.getRandomNumber(0, 10)}' # Horizontal Length
            self.crosshairCode += f';1v;{self.getRandomNumber(0, 10)}' # Vertical Length
            if not outerLineLengthLinked: self.crosshairCode += ';1g;1' # Lengths Linked
            self.crosshairCode += f';1t;{self.getRandomNumber(0, 10)}' # Thickness
            self.crosshairCode += f';1o;{self.getRandomNumber(0, 40)}' # Offset

            if outerMovementError:
                self.crosshairCode += f';1s;{self.getRandomNumber(0, 3, 3)}'; # Multipler
            else:
                self.crosshairCode += ';1m;0'; # Disable
            
            if outerFiringError:
                self.crosshairCode += f';1e;{self.getRandomNumber(0, 3, 3)}'; # Multipler
            else:
                self.crosshairCode += ';1f;0' # Disable

        else:
            self.crosshairCode += ';1b;0'; # Disable

    def sniperSettings(self):
        color = self.getRandomNumber(0, 8)
        showCenterDot = self.chance(90)
        self.crosshairCode += ';S'
        self.crosshairCode += f';c;{color}'

        if color ==  8:
            self.crosshairCode += f';u;{format(random.randint(0, 16777215), "x").upper()}FF;b;1'

        # Center Dot
        if showCenterDot:
            self.crosshairCode += f';o;{self.getRandomNumber(0, 1, 3)}'; # Opacity
            self.crosshairCode += f';s;{self.getRandomNumber(1, 6)}'; # Thickness
        else:
            self.crosshairCode += ';d;0'

    def genCrosshair(self):
        advancedSettings = self.chance(100)
        overrideAllCrosshairs = self.chance(50)
        noSpecCrosshair = self.chance(5)
        fadeOnFire = self.chance(50)

        # Basic Blank Code
        if advancedSettings: 
            self.crosshairCode += ';p;0;s;1'

        if overrideAllCrosshairs: self.crosshairCode += ';c;1'

        # Setup Primary
        self.crosshairCode += ';P'
        if noSpecCrosshair: self.crosshairCode += ';s;0'
        if fadeOnFire: self.crosshairCode += ';f;0'

        self.crosshairSettings()
        if advancedSettings:
            self.crosshairCode += ';A'
            self.crosshairSettings()
            self.sniperSettings()

def setup(bot):
    bot.add_cog(CrosshairCog(bot))
    print('Cog loaded: Crosshair')