import discord
import random
import datetime
from discord.ext import commands

class GunCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.slash_command(name='gun', description='Have the bot randomly generate a loadout for you!')
    async def agent(self, ctx: discord.commands.context.ApplicationContext):
        '''Have the bot randomly generate a loadout for you!'''

        GUN_LIST = ['Stinger', 'Spectre', 'Bucky', 'Judge', 'Bulldog', 'Guardian', 'Phantom', 'Vandal', 'Marshal', 'Operator', 'Ares', 'Odin', 'Outlaw']
        SIDEARM_LIST = ['Classic', 'Shorty', 'Frenzy', 'Ghost', 'Sheriff']

        gun1 = random.choice(GUN_LIST)
        gun2 = gun1
        while gun2 == gun1:
            gun2 = random.choice(GUN_LIST)
        sidearm = random.choice(SIDEARM_LIST)
        
        gunbed=discord.Embed(title='Valorant Gun Randomizer', description='Good Luck, Have Fun', color = discord.Colour.random())
        gunbed.add_field(name='__Gun 1__', value=gun1, inline=True)
        gunbed.add_field(name='__Gun 2__', value=gun2, inline=True)
        gunbed.add_field(name='__Sidearm__', value=sidearm, inline=True)
        gunbed.set_footer(text='Requested by ' + ctx.author.display_name + ' at ' + datetime.datetime.now().strftime(r'%I:%M %p'))
        print('Gun loadout generated by', ctx.author.display_name)
        await ctx.respond(embed=gunbed)

def setup(bot):
    bot.add_cog(GunCog(bot))
    print('Cog loaded: Gun')